---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

**Growth as a data scientist**: Describe how you have improved as a practitioner and student of data science this quarter through your work in the course. Focus specifically on data science concepts and the skills we employed in learning them. Don\'t just give a laundry list of topics that you learned (those are in the syllabus, so we know them already). Focus instead on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth. Explain in this essay how this artifact shows growth in the way you are describing.\

Throughout this quarter I learned several topics each and every week. One of the broader ideas was the dyplr package which was used for the majority of the course. However, the main take away and reoccurring theme from this package was my inability to grasp the syntax. In most of my revisions, I often worked toward fixing errors within my syntax with most of them being the across function. This is most notably seen in Challenge 3 where the old syntax was changed half way through the class. From there, I had to constantly go back and change my code to fit the new updated version. Although I have to remind myself to fix the code, I believe rewriting and properly labeling the function allows me to have a better understanding of syntax for R overall. Not only that, but it helps me recognize how different functions interact with each other. These revisions aided in my code when writing actual functions such as pmap_chr and map_chr in Practice Activity 8 and Lab 8.

Another area of growth for me was trying to implement newer concepts into more recent assignments. In Lab 7 and Lab 9, I experimented with using topics from Week 4 such as pivots and joins in my code that didn't necessarily need them. For some instances, like semi_join(), it was fairly easy to implement, but others such as full_join(), I had to get creative. When I wrote the full_join function, the assignment initially only asked to use our created function on columns in a data set. In order to use full_join(), I had to find a way to compare my written function to the actual rescale function. I did so by creating an id variable that acted as a "key" and used two different data sets that used one of the two functions. Finally, I joined them with the full_join to compare the corresponding columns. By thinking in this way, I believe I improved myself because I got to explore my "creative" side. Additionally, I was able to connect topics that I struggled with in the beginning of the quarter and use them in ways that they usually aren't seen.

Overall, I think my growth in this course stems from repetition and stepping out of my comfort zone. Without these, I don't believe I would be able to improve myself as a practitioner or student of data science.
