---
title: "The Power of Efficiency"
format: html
editor: visual
---

**The power of efficiency**: As we\'ve said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term \"efficiency\" means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Include: What is the definition of \"efficiency\"? What does efficiency look like in statistical computing / data science? What does efficiency allow you to do? Why is efficiency important? Where did you encounter efficiency, and what were some [\"a-ha\" moments](https://www.merriam-webster.com/dictionary/aha%20moment) you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

In relation to statistical computing, I believe that the term efficiency means code that is tidy, easy to read, and most importantly, concise. Some places that I've encountered efficiency and understood its importance was at the beginning of the dyplr package unit. Throughout this unit, we focused on different functions such as mutate(), filter(), and across(). At the start, I would use each function multiple times for the same data set to produce the output I wanted. However as my level of understanding increased, I learned that it was more efficient to write the function once and use commas to separate the multiple instances.

Oxford Languages defines efficiency as "achieving maximum productivity with minimum wasted effort or expense". For statistical computing and data science, efficiency allows the coder to clearly and concisely communicate their thought process behind the output. Code varies from person to person giving efficiency an important role. As a reader, code can be confusing when its not written by yourself. That being said, even code you wrote can be hard to read after years or months of not using it. Additionally, efficiency can minimize the amount of "fluff" in your code. From someone who has never seen the code before, efficiency overall aids them in being able to read it.

My biggest "a-ha" moment about efficiency was in the end of Lab 9. I had written multiple mutate functions because even though the same calculation was being performed, the new column names would be different. This is where Dr. Theobold introduced the .names option from the across function. By using this function with the mutate function, I was able to reduce the amount of code I had by four lines and write it in a way that was easy to understand. As a result, the code is not only easy to read, but it's concise.
